{
 "title": "Guardian Application Dashboard",
 "description": "Monitor metrics for node.js and express router status.",
 "tags": [
  "node.js",
  "express",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nodejs_version_info, instance)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "target", "query": "0.05,0.1,0.2,0.3,0.4,0.5" },
   { "name": "tolerated", "query": "0.1,0.2,0.3,0.4,0.5" },
   { "name": "restarts_interval", "query": "1d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Apdex Score: target $target s, tolerated $tolerated s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n        (   \n                sum(http_request_duration_seconds_bucket{instance=~\"$instance\",le=\"$target\",code=~\"^2..$\"})\n                + (\n                        sum(http_request_duration_seconds_bucket{instance=~\"$instance\",le=\"$tolerated\",code=~\"^2..$\"})\n                        - sum(http_request_duration_seconds_bucket{instance=~\"$instance\",le=\"$target\",code=~\"^2..$\"})\n                ) / 2\n        ) / sum(http_request_duration_seconds_count{instance=~\"$instance\",code=~\"^2..$\"})\n) * 100",
     "legendFormat": "score"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\tsum(\n\t\thttp_request_duration_seconds_count{instance=~\"$instance\",code=~\"^[45]..$\"} OR on() vector(0)\n\t) / \n\tsum(\n\t\thttp_request_duration_seconds_count{instance=~\"$instance\"}\n\t)\n)*100",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "Transferred",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_response_size_bytes_sum{instance=~\"$instance\"}) + sum(http_request_size_bytes_sum{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_response_size_bytes_sum{instance=~\"$instance\"}[$interval])) + sum(rate(http_request_size_bytes_sum{instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Restarts in $restarts_interval",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{instance=~\"$instance\"}[$restarts_interval]))"
    }
   ]
  },
  {
   "title": "Node.js Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Eventloop Latency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
       "legendFormat": "last"
      },
      {
       "expr": "nodejs_eventloop_lag_p99_seconds{instance=~\"$instance\"}",
       "legendFormat": "p99"
      },
      {
       "expr": "nodejs_eventloop_lag_p50_seconds{instance=~\"$instance\"}",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Rate of CPU Time Spent",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$interval])",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Process Memory",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "virtual memory"
      },
      {
       "expr": "process_heap_bytes{instance=~\"$instance\"}",
       "legendFormat": "heap memory"
      }
     ]
    },
    {
     "title": "Number of Open Connections",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "expressjs_number_of_open_connections{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Used File Descriptors",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "( process_open_fds{instance=~\"$instance\"} / process_max_fds{instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Active Handlers/Requests",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nodejs_active_handles_total{instance=~\"$instance\"}",
       "legendFormat": "Active Handler"
      },
      {
       "expr": "nodejs_active_requests_total{instance=~\"$instance\"}",
       "legendFormat": "Active Request"
      }
     ]
    }
   ]
  },
  {
   "title": "Node.js Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Garbage Collection Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Rate of Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_count{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_sum{instance=~\"$instance\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_count{instance=~\"$instance\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "resident"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "external"
    }
   ]
  },
  {
   "title": "Heap Space Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{space}}"
    }
   ]
  },
  {
   "title": "Express Route",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Apdex Score: target $target s, tolerated $tolerated s",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(\n        (   \n                sum(http_request_duration_seconds_bucket{instance=~\"$instance\",le=\"$target\",code=~\"^2..$\"})\n                + (\n                        sum(http_request_duration_seconds_bucket{instance=~\"$instance\",le=\"$tolerated\",code=~\"^2..$\"})\n                        - sum(http_request_duration_seconds_bucket{instance=~\"$instance\",le=\"$target\",code=~\"^2..$\"})\n                ) / 2\n        ) / sum(http_request_duration_seconds_count{instance=~\"$instance\",code=~\"^2..$\"})\n) * 100",
       "legendFormat": "score"
      }
     ]
    },
    {
     "title": "Response Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{instance=~\"$instance\"}[$interval])) by (code,le))",
       "legendFormat": "{{code}}(95%)"
      },
      {
       "expr": "histogram_quantile(1, sum(rate(http_request_duration_seconds_bucket{instance=~\"$instance\"}[$interval])) by (code,le))",
       "legendFormat": "{{code}}(100%)"
      }
     ]
    },
    {
     "title": "Requests Per Seconds",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{instance=~\"$instance\"}[$interval])) by (code)",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Response Size",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(http_response_size_bytes_sum{instance=~\"$instance\"}) by (route)",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Code Count",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(http_request_duration_seconds_count{instance=~\"$instance\"}) by (code)",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Request Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(http_request_duration_seconds_count{instance=~\"$instance\"}) by (route)",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Top 5 Request Duration",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "topk(5, sum by (route)(http_request_duration_seconds_sum{instance=~\"$instance\"}))",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Top 5 Success Duration",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 26 },
     "targets": [
      {
       "expr": "topk(5, sum by (route)(http_request_duration_seconds_sum{instance=~\"$instance\",code=~\"^[23]..$\"}))",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Top 5 Error Duration",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 26 },
     "targets": [
      {
       "expr": "topk(5, sum by (route)(http_request_duration_seconds_sum{instance=~\"$instance\",code=~\"^[45]..$\"}))",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Top 5 Request Count",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "topk(5, sum by (route)(http_request_duration_seconds_count{instance=~\"$instance\"}))",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Top 5 Success Count",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 26 },
     "targets": [
      {
       "expr": "topk(5, http_request_duration_seconds_count{instance=~\"$instance\",code=~\"^[23]..$\"})",
       "legendFormat": "({{code}}) {{route}}"
      }
     ]
    },
    {
     "title": "Top 5 Error Count",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 26 },
     "targets": [
      {
       "expr": "topk(5, http_request_duration_seconds_count{instance=~\"$instance\",code=~\"^[45]..$\"})",
       "legendFormat": "({{code}}) {{route}}"
      }
     ]
    }
   ]
  }
 ]
}